// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError(
      'DefaultFirebaseOptions have not been configured for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEB3Fk_F4u5-sN2jjZ1c0LDrC9shf67ks',
    appId: '1:804957043676:web:80ff9f13e447ba5612ad19',
    messagingSenderId: '804957043676',
    projectId: 'synthanote',
    authDomain: 'synthanote.firebaseapp.com',
    storageBucket: 'synthanote.appspot.com',
  );
}
